name: Join-KR
version: '${project.version}'
main: p.joinkr.Join_KR
api-version: '1.16'
author: Spinnin34
commands:
  version:
    description: "Para saber la version de el plugin"
    usage: "/version"